variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: docker.km3net.de/test/orcasong:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: docker.km3net.de/orcasong:$CI_COMMIT_TAG
  CONTAINER_LATEST_IMAGE: docker.km3net.de/orcasong:latest
  SINGULARITY_IMAGE: orcasong.sif


stages:
  - build-singularity


cache:
  paths:
    - .cache/pip
    - venv/
  key: "$CI_COMMIT_REF_SLUG"


build-singularity:
  image: docker.km3net.de/base/singularity:3.1
  stage: build-singularity
  script:
    - singularity --version
    - singularity build $SINGULARITY_IMAGE Singularity
    - apt-get update -qy
    - apt-get install -qy lftp
    - lftp -d -u $KM3NET_SFTP_USER,$KM3NET_SFTP_PASSWORD sftp://$KM3NET_SFTP_HOST -e "set sftp:auto-confirm yes; set ssl:verify-certificate no; cd singularity/; put $SINGULARITY_IMAGE; bye"
